platform :ios, ‘7.1’

target ‘ProjectBaseSet’ do

  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 3.8.1'
  pod 'Masonry', '~> 1.0.1'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'MJExtension', '~> 3.0.13'


end